# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog2',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='blog1',
            name='blog_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.blog2'),
            preserve_default=False,
        ),
    ]
